### ISSUE TITLE
Boost link error, undefined icu reference

### ISSUE THREAD

**Issue by rickjs** [xoreos/xoreos#531] opened 2019-05-14 23:25 UTC
Using VS2017 and cmake, on build, link gives undefined icu reference. Boost locale object can't find icu. For example libboost_locale-mt.a(icu_backend.o) has undefined reference to `icu_57::Locale::Locale(). I can't change to icu v57 because msys2 mingw62 requires icu v62 for the toolchain. Many errors all with boost locale and icu_57 link errors. I've used boost v1.60 and boost v1.62 with errors.

**Comment by DrMcCoy** [comment] 2019-05-27 18:54
I'm kinda at a loss here, sorry. This sounds to me like a completely broken Boost installation?

How did you install Boost? If you're using MSYS2 and use the ICU from MSYS2, you need to install the boost libraries using pacman within MSYS2 as well. Some parts of Boost depend on ICU, and you do obviously need the ICU version the Boost libraries were compiled against.

(However, you should be able to install multiple versions of ICU at the same time, as long as they're all compiled to have the version number encoded within the soname. You can even link against several different ICU versions within the same project, since ICU can encode the version number into its namespace as well. Not that I'm saying that's what you should do here, but ICU is able to cope with that.)

**Comment by rickjs** [comment] 2019-05-27 20:38
Made mistake, said mingw62, meant mingw64
How did you install Boost?
Used pacman -U mingw64 boost file,1.62 version 

Some parts of Boost depend on ICU,
Yeah, locale does.
 Installing icu 57, let you know results

**Comment by rickjs** [comment] 2019-05-27 20:48
Installed icu 57 using pacman.
Rebuilt common, google test libs.
Using common datetime test for quick build.
Rebuilt common datetime test, same error, boost locale can't find reference to icu_57 objects.
libboost_locale-mt.a(icu_backend.o undefined reference to `icu_57::Locale::Locale()

**Comment by seedhartha** [comment] 2019-05-27 23:40
It's not clear to me, what you're trying to do. If compiling xoreos using VS 2017 and Boost is what you want, you could always install prebuilt Boost libraries from [here] (https://sourceforge.net/projects/boost/files/boost-binaries/) and pass it to CMake as `- DBoost_INCLUDE_DIR`. What do mingw and msys have to do with anything? :)

**Comment by darkstar** [comment] 2022-01-06 02:35
msys/mingw libraries are not compatible with MSVC. You either need boost/icu libraries that were compiled on MSVC, or compile them yourself.

Also make sure that you are using the same runtime in your MSVC build that was used when compiling boost/icu (i.e. /MD, /MT, /MTd, etc.) as otherwise you will get strange crashes

**Comment by DrMcCoy** [comment] 2022-01-06 04:25
Yeah, I'm going ahead and close this issue as not a bug. Feel free to reopen with more information if it still occurs.

**Closed by DrMcCoy** 2022-01-06 04:25 UTC
