### ISSUE TITLE
CMAKE Build - libboost issue / error

### ISSUE THREAD

**Issue by Glog78** [xoreos/xoreos#106] opened 2015-11-29 16:39 UTC
When using the default cmake file i get an libboost error in the linking phase. Attached is verbose build with gcc.

With -DBoost_USE_STATIC_LIBS=off (thanx to DrMcoy) for the hint. It works.

OS: Archlinux current

[buildlog.txt](https://github.com/xoreos/xoreos/files/46667/buildlog.txt)

**Comment by DrMcCoy** [comment] 2015-11-29 18:13
@berenm, can you look at that? Because I have no clue at all there... Thanks!

**Comment by berenm** [comment] 2015-11-30 19:25
I don't really think that the issue is related to xoreos.

I suspect `/usr/lib/hardening-wrapper/bin/c++` to add a `-fPIE` flag to the compilation command-line, which asks for all the code in the `xoreos` executable to be position independent.

This is fine for the dynamic libraries, as they usually are compiled with `-fPIC`, however the code that is imported from static libraries may not be compiled with `-fPIC` and apparently this is the case for the Boost libraries.

**Comment by DrMcCoy** [comment] 2015-12-01 13:35
Hmm, yes, looking at that the file [from the package](https://www.archlinux.org/packages/community/x86_64/hardening-wrapper/), it seems it does add -fPIE when "HARDENING_PIE" is 1, and that's set default in the hardening-wrapper.conf.

I'm closing this then, and add a note to the Compiling xoreos wiki page.

**Closed by DrMcCoy** 2015-12-01 13:35 UTC

**Comment by Glog78** [comment] 2015-12-01 15:40
On the other hand the clang compiler doesn't have -fPIE set (at least not that you can see it somewhere in the build) and still fails. See the following build log:

[buildlog.txt](https://github.com/xoreos/xoreos/files/48691/buildlog.txt)

**Comment by berenm** [comment] 2015-12-01 15:45
But this is not the same error, and this is due to missing -licui18n and -licuuc when using static Boost libraries (dynamic version automatically import the required dependencies).

The lookup for Boost libraries is done using CMake' stock `FindBoost.cmake` which apparently doesn't detect additional dependencies in static mode... The solution is to force Boost_USE_STATIC_LIBS=off in the CMakeLists.txt.

**Comment by DrMcCoy** [comment] 2015-12-01 15:51
> this is due to missing -licui18n and -licuuc when using static Boost libraries

For the record, I have the same issue on my system, yes. And I have been forcing static boost linking off when testing CMake for that reason. It's a bit annoying, but that's an issue with the stack FindBoost.cmake, there's probably nothing we can do about it.

Well, except filing a bug report against CMake... Hmm. I might do that, unless someone else with more indepth CMake knowledge wants to take that up. :P

**Comment by berenm** [comment] 2015-12-01 15:58
I there any advantage allowing static linking with the Boost libraries? Most of the other dependencies are dynamically linked anyway, no?

**Comment by DrMcCoy** [comment] 2015-12-01 16:06
Yes, all the other dependencies are dynamically linked.

Hmm, I had thought you had the static thing in there from the beginning, but I apparently misremember. Sorry. :)
Looks like it came from 24c1de92e78f1e608d7311102d5c12af54740f12 via https://github.com/cc9cii/xoreos/commit/4a436114ea6663e86fb57bd3f03bff8c583039b8. Hmm...

Might be worth defaulting it to OFF?

**Comment by berenm** [comment] 2015-12-01 16:07
> Might be worth defaulting it to OFF?

+1

**Comment by berenm** [comment] 2015-12-01 16:09
Or at least, on OSX/Linux... I don't know what's the situation is on Win32, maybe people there prefer to have the choice of static vs shared Boost in case they compile it themselves.

**Comment by DrMcCoy** [comment] 2015-12-01 16:12
Well, I wouldn't remove it, just change the ON to OFF.

So they'd have to pass "-DBoost_USE_STATIC_LIBS=on" instead of Unix people having to pass "-DBoost_USE_STATIC_LIBS=off".

Hmm, can the option() be wrapped in if(CMAKE_HOST_WIN32), with the true branch setting it to ON and the false branch setting it to OFF? Would that work?

**Comment by berenm** [comment] 2015-12-01 16:15
Sure but I think you're right, changing the default value is good enough. Although if/else would perfectly work, you don't want to end up with a complicated CMakeLists.

**Comment by DrMcCoy** [comment] 2015-12-01 16:23
> you don't want to end up with a complicated CMakeLists

Okay :)
